#include <stddef.h>
#define NOOP(name) void name(void) { }
#define NOOPV(name) void *name(void) { return NULL; }
void glBlitNamedFramebuffer(void) { }
void glCompressedTextureBuffer(void) { }
void glDeleteShader(void) { }
void glCreateBuffer(void) { }
void glDeleteSync(void) { }
void glCreateProgram(void) { }
void *glXGetProcAddress(void) { return NULL; }
void glWindowPos2f(void) { }
void glDebugMessageCallbackARB(void) { }
void glCompressedTexture2D(void) { }
void glTextureImage2D(void) { }
void glDispatchComputeIndirect(void) { }
void glCompressedTexSubImage3D(void) { }
void glUniform4i(void) { }
void glTexGenf(void) { }
void glClipPlane(void) { }
void *glXDestroyWindow(void) { return NULL; }
void glTexCoord2sv(void) { }
void glGetTexGeniv(void) { }
void glTexGeniv(void) { }
void glGenTextures(void) { }
void glGetQueryiv(void) { }
void glTextureStorage1D(void) { }
void *glXGetFBConfigs(void) { return NULL; }
void glDepthRangeIndexed(void) { }
void glShaderSource(void) { }
void glGetQueryObjectiv(void) { }
void glTextureStorage2DArray(void) { }
void glUniform2u(void) { }
void glCompressedSubTexture2DArray(void) { }
void glVertexAttribI4uiv(void) { }
void glRenderbufferStorage(void) { }
void glGetTexGenfv(void) { }
void glSpecializeShader(void) { }
void glTextureView(void) { }
void glCreateContextsAttribs(void) { }
void glUniformMatrix3fv(void) { }
void glPolygonOffsetLine(void) { }
void glGetProgramInfoLog(void) { }
void glPolygonOffsetFactor(void) { }
void glWindowPos3fv(void) { }
void glSampleCoverage(void) { }
void glTexCoord3s(void) { }
void glVertexAttribI3uiv(void) { }
void glValidateProgram(void) { }
void glUniform2f(void) { }
void glTexStorage3DMultisample(void) { }
void glProgramParameteri(void) { }
void glSecondaryColor3b(void) { }
void glFogi(void) { }
void glMakeContextCurrent(void) { }
void glPatchParameterfv(void) { }
void glVertexAttribI1ui(void) { }
void glCopyTextureSubImage1D(void) { }
void glViewport(void) { }
void glGetSynci64_v(void) { }
void glDrawArraysIndirect(void) { }
void glTexGend(void) { }
void glCompressedTexImage3D(void) { }
void glEndTexSubImage(void) { }
void glDrawArrays(void) { }
void glPrioritizeTextures(void) { }
void glBlendEquation(void) { }
int glGetBooleanv(void) { return 0; }
void glPolygonStipple(void) { }
void glTransformFeedbackBufferRange(void) { }
void glNamedFramebufferTexture(void) { }
void glVertexAttrib2f(void) { }
void glTexStorage3D(void) { }
void glUniform3i(void) { }
void glUniform2iv(void) { }
void glProgramUniform4uiv(void) { }
void glTexCoord3i(void) { }
void glVertexAttrib4Nub(void) { }
int glGetFloatv(void) { return 0; }
void glClearBufferSubData(void) { }
void glRasterPos4dv(void) { }
void glWindowPosPointer(void) { }
void glUniform4iv(void) { }
void glTexCoord4sv(void) { }
void glGetMaterialfv(void) { }
void glTexEnvf(void) { }
void glProgramUniform1f(void) { }
void glIsRenderbuffer(void) { }
void glViewportIndexedfv(void) { }
void glProgramUniformMatrix4fv(void) { }
void glProgramUniform3f(void) { }
void glGetTexImage(void) { }
void glVertexAttribI3i(void) { }
void glScissorIndexed(void) { }
void glTextureStorage2DMultisample(void) { }
void glTexCoord2fv(void) { }
void glProgramUniform3iv(void) { }
void glTexGeni(void) { }
void glStencilOpSeparate(void) { }
void glBlendFunc(void) { }
void glNormal3sv(void) { }
void glVertexAttrib4Nubv(void) { }
void glRasterPos4sv(void) { }
void glVertexAttrib4usv(void) { }
void glSampleMaski(void) { }
void *glXGetVisualFromFBConfig(void) { return NULL; }
void glVertexAttribI3ui(void) { }
void glMemoryBarrierByRegion(void) { }
void glGetTexEnvfv(void) { }
void glGetTexLevelSpacing(void) { }
void glObjectPtrLabel(void) { }
void glClearNamedFramebufferuiv(void) { }
void glPrimitiveBoundingBox(void) { }
void glCompressedSubTexture2D(void) { }
void glWindowPos3i(void) { }
void glGetTexEnviv(void) { }
void glWindowPos2fv(void) { }
void *glXDestroyPbuffer(void) { return NULL; }
void glUniform1fv(void) { }
void glVertexAttrib4f(void) { }
void glTexGendv(void) { }
void glEvalMesh2f(void) { }
void glPushAttrib(void) { }
void glTexCoord2d(void) { }
void glEnd(void) { }
void glDeleteTextures(void) { }
void glVertexAttrib4Nsv(void) { }
void glCreateShaderProgramv(void) { }
void glMultiDrawElementsIndirect(void) { }
void glSecondaryColorPointer(void) { }
void glDepthFunc(void) { }
void glPrimitivesRange(void) { }
void glSampleMask(void) { }
void glVertexAttribI4bv(void) { }
void glDeleteProgram(void) { }
void glGetClipPlane(void) { }
void glDrawElementsInstancedBaseVertex(void) { }
void glPopClientAttrib(void) { }
void glMultiDrawArraysInstanced(void) { }
void glTextureBufferRange(void) { }
void glLightfv(void) { }
void *glXMakeCurrent(void) { return NULL; }
void glVertexAttrib4Nbv(void) { }
void glNamedFramebufferParameteri(void) { }
void glMap2f(void) { }
void glCreateShader(void) { }
void glIsTexture(void) { }
void glTexCoord4fv(void) { }
void *glXCopyContext(void) { return NULL; }
void *glXUseXFont(void) { return NULL; }
void *glXGetClientVersion(void) { return NULL; }
void glPointParameterf(void) { }
void glMatrixMode(void) { }
void glGetPixelMapuiv(void) { }
void glGetBufferSubData(void) { }
void glAlphaFunc(void) { }
void glVertexAttrib3d(void) { }
void *glXBindTexImage(void) { return NULL; }
void glBindRenderbuffer(void) { }
void glDisable(void) { }
void glProgramUniform2iv(void) { }
void glUnmapNamedBuffer(void) { }
void glNamedFramebufferDrawBuffers(void) { }
void glTextureSubImage2D(void) { }
void glDeleteRenderbuffers(void) { }
void glFramebufferRenderbuffer(void) { }
void glRasterPos3i(void) { }
void glFinish(void) { }
void glCompressedSubTexture3D(void) { }
void glGenLists(void) { }
void glWindowPos2d(void) { }
void glGetProgramInterfaceiv(void) { }
void glXBadFBConfig(void) { }
void glTexCoord1d(void) { }
void glGetSubroutineIndex(void) { }
void glRotatei(void) { }
void glIsSync(void) { }
void glFrameBufferSynchronized(void) { }
void glVertexAttrib3f(void) { }
int glGetDoublev(void) { return 0; }
void glGetMapdv(void) { }
void glMaterialiv(void) { }
void glClearStencil(void) { }
void glVertexAttrib4ub(void) { }
void glVertexAttribIFormat(void) { }
void glUniform3u(void) { }
void glTexParameteri(void) { }
void glUniform1i(void) { }
void glTexCoord1dv(void) { }
void glVertexAttribFormat(void) { }
void glCreateContexts(void) { }
void glGetUniformLocation(void) { }
void glVertexAttrib1f(void) { }
void glUniform2ui(void) { }
void glMapGrid2f(void) { }
void glMapNamedBuffer(void) { }
void glLightModelfv(void) { }
void glTexCoord2dv(void) { }
void glRotatef(void) { }
void glVertexAttribI2uiv(void) { }
void glGetUniformIndices(void) { }
void *glXCreateGLXPixmap(void) { return NULL; }
void glTextureBufferAttachment(void) { }
void glBufferStorage(void) { }
void glPushClientAttrib(void) { }
void *glXCreateWindow(void) { return NULL; }
void glTextureStorage3DArray(void) { }
void glVertexAttrib4uiv(void) { }
void glGetQueryIndexedv(void) { }
void glCopyTexSubImage2D(void) { }
void glRasterPos4f(void) { }
void glTexParameterf(void) { }
void glGetTextureLevelParameter(void) { }
void glStencilMaskSeparate(void) { }
void glTexCoord4dv(void) { }
void glTransformFeedbackResume(void) { }
void glGetShaderInfoLog(void) { }
void glNormal3bv(void) { }
void glPolygonOffsetEXT(void) { }
void glBlendColor(void) { }
void glUniform2i(void) { }
void glDeleteBuffersEXT(void) { }
void glMapNamedBufferRange(void) { }
void glClearTexImage(void) { }
void glEvalMesh2d(void) { }
void glNormal3dv(void) { }
void glPolygonOffsetFill(void) { }
void glBufferSubData(void) { }
void glRasterPos2i(void) { }
void glTexEnviv(void) { }
void glUnmapBuffer(void) { }
void glGetShaderPrecisionFormat(void) { }
void glGetQueryObjectIndex64v(void) { }
void glVertexAttrib4fv(void) { }
void *glXQueryServerString(void) { return NULL; }
void glTexCoord1iv(void) { }
void glMemoryBarrier(void) { }
void glMultiDrawArraysIndirect(void) { }
void glMultiDrawElements(void) { }
void glUniform4f(void) { }
void glTextureBuffer(void) { }
void glProgramPparameter(void) { }
void glNormal3f(void) { }
void glCullFace(void) { }
void glGenQueries(void) { }
void glTransformFeedbackStreamVaryings(void) { }
void glScalei(void) { }
void glVertexAttrib3s(void) { }
void glTextureParameterf(void) { }
void glTextureStorage3DMultisample(void) { }
void glCompressedSubTextureImage(void) { }
void glBindBufferRangeEXT(void) { }
void glClearBufferData(void) { }
void glOrtho(void) { }
void glSelectBuffer(void) { }
void glResumeTransformFeedback(void) { }
void glGetRenderbufferParameteriv(void) { }
void glTexCoord1s(void) { }
void glGetUniformSubroutine(void) { }
void glVertexAttribI4iv(void) { }
void glGetBufferParameteriv(void) { }
void glWaitSync(void) { }
void glProgramUniform4f(void) { }
void glNamedFramebufferTextureMultisample(void) { }
void glCompressedTexture2DArray(void) { }
void glStencilMask(void) { }
void glTextureStorage3D(void) { }
void glBindBufferBase(void) { }
int glXSwapInterval(void) { return 0; }
void glGetProgramiv(void) { }
void glBlendEquationSeparate(void) { }
void glPauseTransformFeedback(void) { }
void glTexCoord4iv(void) { }
void glEndTexImage(void) { }
void glClearColor(void) { }
void glLineWidthRanged(void) { }
void glSecondaryColor3i(void) { }
void glUseProgramStages(void) { }
void glClearDepth(void) { }
void glGetPixelMapfv(void) { }
void glScissorIndexedv(void) { }
void glProgramUniform4ui(void) { }
void glCreateBuffers(void) { }
void glRasterPos3dv(void) { }
void glMapBufferRange(void) { }
void glTexCoord3d(void) { }
void glDepthRangef(void) { }
void glIsNamedFramebuffer(void) { }
void glEnable(void) { }
void glCompressedTexture3D(void) { }
void glUseProgram(void) { }
void glDeleteFramebuffers(void) { }
void glWindowPos2iv(void) { }
void glMinSampleShading(void) { }
void glGetLightiv(void) { }
void glPointSize(void) { }
void glUniform4fv(void) { }
void glGetProgramResourceIndex(void) { }
void glTransformFeedbackVaryings(void) { }
void glVertexAttribI3iv(void) { }
void glUniform4uiv(void) { }
void glFogCoordPointer(void) { }
void glMapGrid1d(void) { }
void glVertexAttribI2ui(void) { }
void glCopyImageSubData(void) { }
void glTextureImage1D(void) { }
void glClampColor(void) { }
void glLightf(void) { }
void glActiveTexture(void) { }
void glMap2d(void) { }
void glTexImage1D(void) { }
void glDepthMask(void) { }
void glGetMaterialiv(void) { }
void glCopyTexture1D(void) { }
void glTextureBufferStorage(void) { }
void glGetNamedBufferSubData(void) { }
void glNormal3iv(void) { }
void glDrawElementsIndirect(void) { }
void glUniform1u(void) { }
void glVertexAttrib4sv(void) { }
void glTextureSubImage3D(void) { }
void glTexCoord2iv(void) { }
void glTextureParameterfv(void) { }
void glRasterPos4iv(void) { }
void glTexImage2D(void) { }
void glVertexAttrib4s(void) { }
void glBufferView(void) { }
void glRenderMode(void) { }
void glGetSynciv(void) { }
void glEndTransformFeedback(void) { }
void glBindFramebuffer(void) { }
void glEvalCoord1d(void) { }
void glUniform3ui(void) { }
void glStartTexImage(void) { }
void glVertexAttrib2fv(void) { }
void glShadeModel(void) { }
void glStencilOp(void) { }
void glCompressedSubTexture1DArray(void) { }
void glGetLightfv(void) { }
void glProgramUniform1fv(void) { }
void glGetNamedBufferPointerv(void) { }
void glRasterPos2s(void) { }
void glCopyTexSubImage1D(void) { }
void glProvokingVertex(void) { }
void glInvalidateBufferSubData(void) { }
void glScissor(void) { }
void glProgramUniform4xv(void) { }
void glTexStorage1DMultisample(void) { }
void glMapGrid1f(void) { }
void glMultiDrawElementsInstancedBaseVertex(void) { }
void glDrawBuffers(void) { }
void glLightModeliv(void) { }
void glTexCoord3dv(void) { }
void glSampleMasks(void) { }
void glLogicOp(void) { }
void glTexStorage2D(void) { }
void glReadPixels(void) { }
void glGetTextureImage(void) { }
void glGetNamedString(void) { }
void glDispatchCompute(void) { }
void glNormal3i(void) { }
void glWindowPos3iv(void) { }
void glVertexAttrib3fv(void) { }
void glEvalCoord2f(void) { }
void glProgramUniformMatrix3fv(void) { }
void glPointSizeRanged(void) { }
void glVertexAttribI4usv(void) { }
void glClearNamedBufferData(void) { }
void glProgramUniform3fv(void) { }
void *glXChooseFBConfig(void) { return NULL; }
void glWindowPos3f(void) { }
void glCompressedTexImage2D(void) { }
void glVertexAttrib1d(void) { }
void glIsBuffer(void) { }
void glProgramUniform2uiv(void) { }
void *glXQueryExtensionString(void) { return NULL; }
void glTexCoord4f(void) { }
void glProgramUniform3xv(void) { }
void glMultiDrawArrays(void) { }
void glCopyTexture2D(void) { }
void *glXCreatePbufferCrisp(void) { return NULL; }
void glCompressedTexSubImage2D(void) { }
void glRasterPos4s(void) { }
void glUseProgramStage(void) { }
void glStartTexSubImage(void) { }
void glGetContexts(void) { }
void glVertexAttribI2iv(void) { }
void glRasterPos2d(void) { }
void glPopAttrib(void) { }
void glVertexAttrib2s(void) { }
void glTextureStorage2D(void) { }
void glTexCoord3f(void) { }
void glNormal3d(void) { }
void glEvalCoord1f(void) { }
void *glXIsDirect(void) { return NULL; }
void glSecondaryColor3iv(void) { }
void glGenerateMipmap(void) { }
void glCopyTexImage1D(void) { }
void glTexEnvi(void) { }
void glGetActiveAttrib(void) { }
void glLineWidthRange(void) { }
void glFeedbackBuffer(void) { }
void glTexImage3DArray(void) { }
void glProgramUniform3i(void) { }
void glRasterPos3d(void) { }
void glVertexAttribI4ubv(void) { }
void glVertexAttribI2i(void) { }
void glVertexAttribIPointer(void) { }
void *glXDestroyContext(void) { return NULL; }
void glFramebufferTexture1D(void) { }
int glGetError(void) { return 0; }
void glMap1f(void) { }
void glTexCoord1sv(void) { }
void glDrawElementsInstanced(void) { }
void glTranslatef(void) { }
void glProgramUniform2fv(void) { }
void glTexStorage2DMultisample(void) { }
void glPushName(void) { }
void glVertexAttribLFormat(void) { }
void glFogf(void) { }
void *glXCreateNewContext(void) { return NULL; }
void *glXGetSelectedFBConfig(void) { return NULL; }
void *glGetStringi(void) { return NULL; }
void *glXGetProcAddressARB(void) { return NULL; }
void glTexImage2DMultisample(void) { }
void glIsFramebuffer(void) { }
void glEvalCoord2d(void) { }
void glTextureParameteri(void) { }
void glFramebufferTexture3D(void) { }
void glIndexMaterial(void) { }
void glTexCoord4i(void) { }
void glDeleteLists(void) { }
void glCopyPixels(void) { }
void glIndexPointer(void) { }
void glFogfv(void) { }
void glRasterPos4d(void) { }
void glVertexAttrib4ubv(void) { }
void glTransformFeedbackPause(void) { }
void glFenceSync(void) { }
void glProgramUniform2f(void) { }
void glClientWaitSync(void) { }
void glColorMask(void) { }
void glDebugMessageCallback(void) { }
void glCompressedSubTexture1D(void) { }
void glTexCoord3fv(void) { }
void glObjectLabel(void) { }
void glRasterPos3f(void) { }
void glInterpolateTextures(void) { }
void glGetTexLevelParameteriv(void) { }
void glEndQueryIndexed(void) { }
void glUniformMatrix2fv(void) { }
void glUniform1uiv(void) { }
void glTexCoord2s(void) { }
void glRasterPos3sv(void) { }
void *glXGetWindowAttribute(void) { return NULL; }
void glProgramUniform3ui(void) { }
void glCreateFramebuffer(void) { }
void glTextureSubImage1D(void) { }
void glVertexAttribPointer(void) { }
int glGetIntegerv(void) { return 0; }
void glDrawElementsBaseVertex(void) { }
void glGetQueryObjectui64v(void) { }
void glIndexMask(void) { }
void glDrawElements(void) { }
void glMultiDrawElementsBaseVertex(void) { }
void glPixelStorei(void) { }
void glProgramUniform1ui(void) { }
void glTexCoord4d(void) { }
void glPixelMapuiv(void) { }
void glTranslated(void) { }
void glAttachShader(void) { }
void glRasterPos2dv(void) { }
void glDrawArraysInstanced(void) { }
void glTexImage2DArray(void) { }
void glGenBuffers(void) { }
void glCompressedTexSubImage1D(void) { }
void glRasterPos2fv(void) { }
void glBindBufferRange(void) { }
void glProgramUniform1iv(void) { }
void glProgramUniform2ui(void) { }
void glClientActiveTexture(void) { }
void glProgramUniform2i(void) { }
void glProgramUniform1xv(void) { }
void glLightModeli(void) { }
void glUniform2fv(void) { }
void glRetainMode(void) { }
void glGetMapiv(void) { }
void glDebugMessageInsert(void) { }
void glMapGrid2d(void) { }
int glIsEnabled(void) { return 0; }
void glTexCoord1i(void) { }
void glInvalidateFramebuffer(void) { }
void glGetActiveUniformsiv(void) { }
void glLineWidth(void) { }
void glLinkProgram(void) { }
void glMaterialf(void) { }
void glFlush(void) { }
void *glXCreateContext(void) { return NULL; }
void glTexCoord1fv(void) { }
void glProgramUniform1i(void) { }
void glTexCoord2i(void) { }
void glDrawPixels(void) { }
void glMateriali(void) { }
void glGetShaderiv(void) { }
void glTextureBarrier(void) { }
void glSecondaryColor3fv(void) { }
void glTexSubImage3D(void) { }
void glVertexAttrib2sv(void) { }
void glSecondaryColor3dv(void) { }
void glTexSubImage2D(void) { }
void *glXQueryContext(void) { return NULL; }
void glPolygonMode(void) { }
void glSecondaryColor3bv(void) { }
void glEndList(void) { }
void glProgramUniform3uiv(void) { }
void glReadBuffer(void) { }
void glSecondaryColor3f(void) { }
void glVertexAttrib4d(void) { }
void glProgramUniform2xv(void) { }
void *glXFBConfigVisualID(void) { return NULL; }
void glCreateRenderbuffers(void) { }
void glProgramUniform4i(void) { }
void glNormal3b(void) { }
void glTexCoord1f(void) { }
void glBindBuffer(void) { }
void glPushDebugGroup(void) { }
void glNormal3fv(void) { }
void glHint(void) { }
void glTexCoordPointer(void) { }
void glTexEnvfv(void) { }
void glReadnPixels(void) { }
void glCullFaceIndex(void) { }
void *glXCreatePbuffer(void) { return NULL; }
void glRasterPos3fv(void) { }
void glEvalMesh1d(void) { }
void glSecondaryColor3d(void) { }
void glGetProgramResourceName(void) { }
void glClearTexSubImage(void) { }
void glClear(void) { }
void glCompressedTexture1D(void) { }
void glTexParameteriv(void) { }
void glRasterPos2iv(void) { }
void *glXGetConfig(void) { return NULL; }
void glTexParameterfv(void) { }
void glVertexAttribI4ui(void) { }
void glRasterPos2sv(void) { }
void glProgramUniform1uiv(void) { }
void glFramebufferParameteri(void) { }
void *glXGetFBConfigAttrib(void) { return NULL; }
void glPrimitiveBoundingBoxArgv(void) { }
void glUniform3fv(void) { }
void glSecondaryColor3sv(void) { }
void glGetProgramResourceiv(void) { }
void glNormalPointer(void) { }
void glTexSubImage1D(void) { }
void glVertexAttrib4Niv(void) { }
void glDrawRangeElements(void) { }
void glRasterPos4fv(void) { }
void glPixelMapfv(void) { }
void glVertexAttrib1dv(void) { }
void glDrawBuffer(void) { }
void glInitNames(void) { }
void glPopName(void) { }
void glCompressedTexture1DArray(void) { }
void glDebugMessageControl(void) { }
void glTextureImage3D(void) { }
void glScissorArray(void) { }
void glCopyTexImage2D(void) { }
void glGetMapfv(void) { }
void glRasterPos3s(void) { }
void glUniform1ui(void) { }
void glUniform4ui(void) { }
void glGetFragDataIndex(void) { }
void glDepthBoundsEXT(void) { }
void glBeginQuery(void) { }
int glXSwapIntervalMESA(void) { return 0; }
void glWindowPos3d(void) { }
void glFrontFace(void) { }
void glMap1d(void) { }
void glTextureRange(void) { }
void glTransformFeedbackBufferBase(void) { }
void glUniform4u(void) { }
void glInterleavedArrays(void) { }
void glRasterPos4i(void) { }
void glVertexAttrib2d(void) { }
void glUniform3iv(void) { }
void glEndQuery(void) { }
void glRenderbufferStorageMultisample(void) { }
void glVertexAttrib1s(void) { }
void glSampleMaskf(void) { }
void *glXQuerySupportedFBConfigAttributes(void) { return NULL; }
void glViewportIndexedf(void) { }
void glBindBufferBaseEXT(void) { }
void glRasterPos3iv(void) { }
void glPrimitivesBoundingBoxArgv(void) { }
void glUniform3uiv(void) { }
void *glXQueryVersion(void) { return NULL; }
void glFrustum(void) { }
void glProgramUniform4iv(void) { }
void *glXCreateContextAttribsARB(void) { return NULL; }
int glGetInteger64i_v(void) { return 0; }
void glClearNamedFramebufferiv(void) { }
void glUniform1f(void) { }
void glUniformMatrix4fv(void) { }
void *glXQueryExtension(void) { return NULL; }
void glScalef(void) { }
void glCopyNamedBufferSubData(void) { }
void glStringi(void) { }
void glNormal3s(void) { }
void glCompressedTexImage1D(void) { }
void glXDestroyGLXPixmap(void) { }
void glWindowPos3dv(void) { }
void glVertexAttrib1sv(void) { }
void glBeginQueryIndexed(void) { }
void glLighti(void) { }
void glDestroyContexts(void) { }
void glVertexAttribI4i(void) { }
void glCompileShader(void) { }
void glDisablei(void) { }
void glClearNamedBufferSubData(void) { }
void glPointParameteri(void) { }
void glDeleteQueries(void) { }
void glCopyTextureSubImage3D(void) { }
void glVertexAttribI1i(void) { }
void glVertexAttribDivisor(void) { }
void glStencilFuncSeparate(void) { }
void glCopyTexSubImage3D(void) { }
void glTexCoord4s(void) { }
void glNewList(void) { }
void glGetBufferPointerv(void) { }
void glSecondaryColor3s(void) { }
void glMultiDrawElementsInstanced(void) { }
void glVertexAttribI1iv(void) { }
void glUniform3f(void) { }
void glMapBuffer(void) { }
void glNamedFramebufferReadBuffer(void) { }
void glScissorArrayv(void) { }
void glLightModelf(void) { }
void glPointSizeRange(void) { }
void glFogiv(void) { }
void *glXReleaseTexImage(void) { return NULL; }
void *glXSwapBuffers(void) { return NULL; }
void glTexCoord3iv(void) { }
void glTextureParameteriv(void) { }
void glPolygonOffset(void) { }
void glEnablei(void) { }
void glVertexAttribI1uiv(void) { }
void glOrthof(void) { }
void glPixelStoref(void) { }
void glClearNamedFramebufferfv(void) { }
void glProgramUniformMatrix2fv(void) { }
void glInvalidateNamedFramebuffer(void) { }
void glWindowPos2i(void) { }
void glBlendFuncSeparate(void) { }
void glUniform1iv(void) { }
void glVertexAttribI4sv(void) { }
void glVertexAttrib1fv(void) { }
void *glXDestroyPbufferCrisp(void) { return NULL; }
void glLightiv(void) { }
void glMaterialfv(void) { }
void glGetCompressedTextureImage(void) { }
void glPrimitivesBoundingBox(void) { }
void glTexImage3DMultisample(void) { }
void glProgramUniform4fv(void) { }
void glCopyTextureSubImage2D(void) { }
void glUniform2uiv(void) { }
void glVertexAttrib2dv(void) { }
void glTexCoord2f(void) { }
void glDisableIndexed(void) { }
void *glXChooseVisual(void) { return NULL; }
void glGetActiveUniform(void) { }
void glFlushMappedBufferRange(void) { }
void glCreateSync(void) { }
void glTexStorage1D(void) { }
void glIsTransformFeedback(void) { }
void glVertexAttrib3sv(void) { }
void glPatchParameteri(void) { }
void glTexCoord3sv(void) { }
void glDetachShader(void) { }
void *glXGetCurrentContext(void) { return NULL; }
void glGetPolygonStipple(void) { }
void glFlushBufferRange(void) { }
void glRasterPos2f(void) { }
void glEvalMesh1f(void) { }
void glFramebufferTexture2D(void) { }
void glDrawRangeElementsBaseVertex(void) { }
void *glGetString(void) { return NULL; }
void glVertexAttrib3dv(void) { }
void glGetFramebufferAttachmentParameteriv(void) { }
void glStencilFunc(void) { }
void glGetNamedBufferParameteriv(void) { }
void glBufferData(void) { }
int glGetPointerv(void) { return 0; }
void glEdgeFlag(void) { }
void glBlitFramebuffer(void) { }
void glPopDebugGroup(void) { }
void glTexGenfv(void) { }
void glVertexAttrib4dv(void) { }
int glXGetSwapIntervalMESA(void) { return 0; }
void glTexImage3D(void) { }
void glWindowPos2dv(void) { }
void *glXGetCurrentDisplay(void) { return NULL; }
void *glXGetCurrentDrawable(void) { return NULL; }
void *glXMakeContextCurrent(void) { return NULL; }
